/**
 * test-capi.mjs
 * Auto-generated by setup-and-test-capi.ps1
 * Sends one fake QualifiedLead event to Meta CAPI to verify credentials.
 */

const PIXEL_ID = "cls";
const ACCESS_TOKEN = "cls";
const META_API_VERSION = "v19.0";

async function sendTestEvent() {
  const crypto = await import("crypto");
  const hash = (value) =>
    crypto.createHash("sha256").update(value.trim().toLowerCase()).digest("hex");

  const testPhone = "919999999001";
  const eventId = `test_evt_${Date.now()}`;

  const payload = {
    data: [
      {
        event_name: "QualifiedLead",
        event_time: Math.floor(Date.now() / 1000),
        event_id: eventId,
        action_source: "website",
        event_source_url: "https://www.healviacare.in/",
        user_data: {
          ph: [hash(testPhone)],
        },
        custom_data: {
          treatment: "Test Treatment",
          test_run: "true",
        },
      },
    ],
  };

  console.log("Sending test event to Meta CAPI...");
  console.log("Pixel ID:", PIXEL_ID);
  console.log("Event ID:", eventId);
  console.log("");

  try {
    const res = await fetch(
      `https://graph.facebook.com/${META_API_VERSION}/${PIXEL_ID}/events?access_token=${ACCESS_TOKEN}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      }
    );

    const data = await res.json();

    if (!res.ok) {
      console.error("FAILED - Meta rejected the request.");
      console.error("Status code:", res.status);
      console.error("Meta's error response:");
      console.error(JSON.stringify(data, null, 2));
      console.error("");
      console.error("Common causes:");
      console.error("- Wrong Pixel ID");
      console.error("- Access token expired or invalid");
      console.error("- Access token doesn't have permission for this Pixel");
      process.exit(1);
    }

    console.log("SUCCESS - Meta accepted the event.");
    console.log("Meta's response:");
    console.log(JSON.stringify(data, null, 2));
    console.log("");
    console.log("Next step: go to Meta Events Manager -> your Pixel -> 'Test Events' tab");
    console.log("You should see a 'QualifiedLead' event appear there within a few seconds.");
  } catch (err) {
    console.error("FAILED - Network or unexpected error:");
    console.error(err);
    process.exit(1);
  }
}

sendTestEvent();
